ifneq ($(TARGET_SIMULATOR),true)
ifeq ($(TARGET_ARCH),arm)

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := reboot.c
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE := reboot
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_STATIC_LIBRARIES := libstdc++ libc libm libcutils
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_LDLIBS := -static
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := unyaffs.c
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE := unyaffs
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_STATIC_LIBRARIES := libunyaffs
LOCAL_STATIC_LIBRARIES += libstdc++ libc libm libcutils
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_LDLIBS := -static
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := mkyaffs2image.c
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE := mkyaffs2image
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_STATIC_LIBRARIES := libmkyaffs2image
LOCAL_STATIC_LIBRARIES += libstdc++ libc libm libcutils
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_LDLIBS := -static
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := busybox.c
LOCAL_MODULE_TAGS := eng
LOCAL_MODULE := busybox
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_STATIC_LIBRARIES := libbusybox libclearsilverregex 
LOCAL_STATIC_LIBRARIES += libstdc++ libc libm libcutils
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_LDLIBS := -static
include $(BUILD_EXECUTABLE)

endif   # TARGET_ARCH == arm
endif   # !TARGET_SIMULATOR
